import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { migrate } from 'drizzle-orm/libsql/migrator';

import { db, libsql } from '../client.js';
import { runtimeBaseDir } from '../../../config.js';

const dbVersion = '20210502081522';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sourceMigrationsFolder = path.join(__dirname, 'migrations');
const runtimeMigrationsFolder = path.join(runtimeBaseDir, 'migrations');

const getMigrationsFolder = (): string =>
  fs.existsSync(runtimeMigrationsFolder) ? runtimeMigrationsFolder : sourceMigrationsFolder;

const hasTable = async (tableName: string): Promise<boolean> => {
  const result = await libsql.execute({
    sql: "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?;",
    args: [tableName],
  });
  return result.rows.length > 0;
};

const hasCurrentSchema = async (): Promise<boolean> => hasTable('t_circle');

const hasDrizzleMigrations = async (): Promise<boolean> => hasTable('__drizzle_migrations');

const getMigrationFiles = (): string[] => {
  const migrationsFolder = getMigrationsFolder();
  if (!fs.existsSync(migrationsFolder)) return [];
  return fs
    .readdirSync(migrationsFolder)
    .filter((name) => fs.statSync(path.join(migrationsFolder, name)).isDirectory())
    .sort();
};

const initDrizzleMigrationsForExistingDb = async (): Promise<void> => {
  await libsql.execute(`
    CREATE TABLE IF NOT EXISTS __drizzle_migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hash TEXT NOT NULL UNIQUE,
      created_at INTEGER
    );
  `);

  const migrationFiles = getMigrationFiles();
  for (const migrationName of migrationFiles) {
    const migrationPath = path.join(getMigrationsFolder(), migrationName, 'migration.sql');
    if (!fs.existsSync(migrationPath)) continue;

    const hash = fs.readFileSync(migrationPath, 'utf-8');
    const hashSum = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(hash));
    const hashHex = Array.from(new Uint8Array(hashSum))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');

    await libsql.execute({
      sql: 'INSERT OR IGNORE INTO __drizzle_migrations (hash, created_at) VALUES (?, ?);',
      args: [hashHex, Math.floor(Date.now() / 1000)],
    });
  }
};

// Schema definitions live in tables.js; migration files are generated by drizzle-kit.
const createSchema = async (): Promise<void> => {
  const isExistingDb = await hasCurrentSchema();
  const hasMigrationTable = await hasDrizzleMigrations();

  if (isExistingDb && !hasMigrationTable) {
    console.log(' * 检测到旧数据库，正在初始化迁移记录...');
    await initDrizzleMigrationsForExistingDb();
  }

  if (!isExistingDb) {
    await libsql.execute('DROP TABLE IF EXISTS __drizzle_migrations;');
  }

  await migrate(db, { migrationsFolder: getMigrationsFolder() });

  if (isExistingDb) {
    console.log(' * 数据库结构升级完成.');
  } else {
    console.log(' * 成功构建数据库结构.');
  }
};

export { createSchema, dbVersion };
