name: Build artifacts

on:
  push:
    branches-ignore:
      - "dependabot/**"
    tags:
      - v*

jobs:
  build-front-end:
    runs-on: ubuntu-22.04
    name: Build front end PWA from source
    steps:
      - name: Check out latest front end
        uses: actions/checkout@v2
        with:
          repository: kikoeru-project/kikoeru-quasar
          ref: unstable

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install -g @quasar/cli
      - run: npm ci
      - run: quasar build && quasar build -m pwa

      - name: Upload PWA
        uses: actions/upload-artifact@v2
        with:
          name: PWA-unstable
          path: dist/pwa
          if-no-files-found: error

      - name: Upload SPA
        uses: actions/upload-artifact@v2
        with:
          name: SPA-unstable
          path: dist/spa
          if-no-files-found: error

  build:
    needs: build-front-end
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            node_version: 24
            archive_name_prefix: kikoeru-linux-x64

          - os: macos-14
            node_version: 24
            archive_name_prefix: kikoeru-darwin-x64

          - os: windows-2022
            node_version: 24
            archive_name_prefix: kikoeru-win-x64

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm ci

      - run: npm test

      - name: Get branch or tag name
        id: source_name
        run: echo ::set-output name=SOURCE_NAME::${GITHUB_REF##*/}

      - name: Download front-end artifact (PWA)
        uses: actions/download-artifact@v2
        with:
          name: PWA-unstable
          path: dist

      - name: Build backend bundle
        run: npm run build

      - name: Remove development dependencies
        run: npm prune --omit=dev

      - name: Create archive
        run: |
          set -e
          mkdir -p ${archive_name}
          cp -R build ${archive_name}/
          mkdir -p ${archive_name}/build/config ${archive_name}/build/sqlite ${archive_name}/build/covers ${archive_name}/build/VoiceWork
          cp -R node_modules ${archive_name}/
          cp package.json package-lock.json ${archive_name}/
        env:
          archive_name: ${{ matrix.archive_name_prefix }}-${{ steps.source_name.outputs.SOURCE_NAME }}

      - name: Prepare release archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.archive_name_prefix }}-${{ steps.source_name.outputs.SOURCE_NAME }}
          path: ${{ matrix.archive_name_prefix }}-${{ steps.source_name.outputs.SOURCE_NAME }}
          if-no-files-found: error

  build-docker:
    runs-on: ubuntu-22.04
    name: Prepare multiarch docker images
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/unstable') || startsWith(github.ref, 'refs/heads/stable')
    needs: build

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU for cross platform builds
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get branch or tag name
        id: source_name
        run: echo ::set-output name=SOURCE_NAME::${GITHUB_REF##*/}

      - uses: haya14busa/action-cond@v1
        name: Decide front-end version
        id: front_version
        with:
          cond: startsWith(github.ref, 'refs/tags/')
          if_true: ${{ steps.source_name.outputs.SOURCE_NAME }}
          if_false: "unstable"

      - name: Show conditional value from previous step
        run: echo "${{ steps.front_version.outputs.value }}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          pull: true
          tags: |
            muveex/kikoeru-express:${{ steps.source_name.outputs.SOURCE_NAME }}
            muveex/kikoeru-express:dev
            muveex/kikoeru:${{ steps.source_name.outputs.SOURCE_NAME }}
            muveex/kikoeru:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args:
            FRONTEND_VERSION=${{ steps.front_version.outputs.value }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  test-release-archive:
    runs-on: ${{ matrix.os }}
    name: Test release archive on ${{ matrix.os }} x64
    needs: [build]

    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            archive_name_prefix: kikoeru-linux-x64

          - os: macos-14
            archive_name_prefix: kikoeru-darwin-x64

          - os: windows-2022
            archive_name_prefix: kikoeru-win-x64

    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 24

      - name: Get branch or tag name
        id: source_name
        run: echo ::set-output name=SOURCE_NAME::${GITHUB_REF##*/}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.archive_name_prefix }}-${{ steps.source_name.outputs.SOURCE_NAME }}

      - name: List files
        run: ls -al .

      - name: Test bundled server on *nix
        if: ${{ matrix.os == 'ubuntu-22.04' || matrix.os == 'macos-14' }}
        run: |
          set -e
          nohup node build/server.js &
          sleep 10 && cat nohup.out 2>/dev/null &&
          curl --fail -I http://localhost:8888/
          pkill -TERM node

      - name: Test bundled server on Windows
        if: ${{ matrix.os == 'windows-2022' }}
        shell: pwsh
        run: |
          $PSVersionTable
          Start-Job { node build/server.js }
          sleep 5
          Get-Job | Receive-Job
          sleep 5
          curl --fail -I http://localhost:8888/
          Get-Job | Stop-Job
          Get-Job | Remove-Job

  test-docker-image:
    runs-on: ubuntu-latest
    name: Test Docker image on linux/amd64
    needs: build-docker
    container: 'muveex/kikoeru:dev'

    steps:
      - name: Show running process
        run: ps -a

      - name: Test
        run: |
          set -e
          apk update && apk add curl
          nohup node /usr/src/kikoeru/build/server.js &
          sleep 10 && cat nohup.out 2>/dev/null &&
          curl --fail -I http://localhost:8888/
          pkill -TERM node

  publish:
    runs-on: ubuntu-22.04
    name: Prepare release draft
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test-release-archive]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Packup artifacts
        run: cd artifacts && for i in */; do zip -r "${i%/}.zip" "$i"; done

      - name: List artifacts
        run: ls -al artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files:
            artifacts/kikoeru-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
